CREATE TABLE member01(
    mno NUMBER(4)
        CONSTRAINT MEMB01_NO_PK PRIMARY KEY,
    id  VARCHAR2(10 CHAR)
        CONSTRAINT MEMB01_ID_UK UNIQUE
        CONSTRAINT MEMB01_ID_NN NOT NULL,
    name VARCHAR2(10 CHAR)
        CONSTRAINT MEMB01_NAME_NN NOT NULL,
    mail VARCHAR2(50 CHAR)
        CONSTRAINT MEMB01_MAIL_UK UNIQUE
        CONSTRAINT MEMB01_MAIL_NN NOT NULL,
    tel VARCHAR2(13 CHAR)
        CONSTRAINT MEMB01_TEL_UK UNIQUE
        CONSTRAINT MEMB01_TEL_NN NOT NULL,
    gen CHAR(1)
        CONSTRAINT MEMB01_GEN_CK CHECK (gen IN ('F','M'))
        CONSTRAINT MEMB01_GEN_NN NOT NULL,
    avt NUMBER(2)
        CONSTRAINT MEMB01_AVT_NN NOT NULL
        CONSTRAINT MEMB01_AVT_FK REFERENCES avatar(ano),
    isshow CHAR(1) DEFAULT 'Y'
        CONSTRAINT MEMB01_SHOW_NN NOT NULL
        CONSTRAINT MEMB01_SHOW_CK CHECK (isshow IN('Y','N'))--활동여부

);


CREATE TABLE AVATAR
AS 
    SELECT
        *
    FROM
        FREE.AVATAR;
        
        
ALTER TABLE  AVATAR
ADD CONSTRAINT AVT_NO_PK PRIMARY KEY(ANO);




------------------------

INSERT INTO
    MEMBER01(MNO,ID,NAME,MAIL,TEL,GEN,AVT)
VALUES(
    1000, 'WOONG','서현웅','MYGUSDND@GMAIL.COM',
    '010-1234-1234','M',11
);

INSERT INTO
    MEMBER01(MNO,ID,NAME,MAIL,TEL,GEN,AVT)
VALUES(
    1001, 'EUNS','전은석','EUNS@INCREPAS.COM',
    '010-3175-9042','M',14
);

INSERT INTO
    MEMBER01(MNO,ID,NAME,MAIL,TEL,GEN,AVT)
VALUES(
    1002, 'JUN','전준우','JUN@GMAIL.COM',
    '010-5795-5484','M',12
);

commit;

ALTER TABLE
    MEMBER01
ADD
    joinDate DATE DEFAULT sysdate
    CONSTRAINT MEMB01_JDAY_NN NOT NULL;