CREATE TABLE EMP
AS
SELECT * FROM SCOTT.EMP;

DESC EMP;

CREATE INDEX EMPNOIDX
ON 
    EMP(EMPNO);
    
DROP INDEX EMPNOIDX;
CREATE UNIQUE INDEX EMPNOIDX
ON EMP(EMPNO);

SELECT EMPNO FROM EMP;

ALTER TABLE EMP
ADD CONSTRAINT SEO_NO_PK PRIMARY KEY(EMPNO);

CREATE VIEW V_DEPT
AS SELECT * FROM SCOTT.DEPT;

GRANT SELECT ON V_DEPT TO PUBLIC;
CREATE PUBLIC SYNONYM SY_VDEPT
FOR SCOTT.V_DEPT;

ALTER TABLE V_DEPT
ADD CONSTRAINT VEMP_DEPTNO_PK PRIMARY KEY(DEPTNO);

ALTER TABLE EMP
ADD CONSTRAINT SEO_DEPTNO_FK FOREIGN KEY(DEPTNO) REFERENCES SY_VDEPT(DEPTNO);
DESC SY_VDEPT;

DROP VIEW V_DEPT;

DROP 
